# Generated by Django 2.1 on 2020-10-21 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filters',
            name='bigc',
        ),
        migrations.RemoveField(
            model_name='filters',
            name='month',
        ),
        migrations.RemoveField(
            model_name='filters',
            name='year',
        ),
    ]
